### ISSUE TITLE
get_last_codes() only returns circuits run from the Quantum Experience website.

### ISSUE THREAD

**Issue by ry-dgel** [IBM/qiskit-api-py#13]
I have a few units that are locked up in experiments that timed out while using the SDK and so I don't have the job IDs to retrieve them.

The get_last_codes() function seems like it would be useful for retrieving these job IDs, however it only returns a few of the circuits that I ran on the Quantum Experience website via the score editor instead of the circuits that I've run recently through the sdk/api.

This seems to be more of an issue with how the backend stores the circuits that have been run, but I figure this may be the place to mention it.

**Comment by pacomf** [comment]
Yes, you are right, maybe in the next version we can do a method to get all the jobs by user.
 
We add to out backlog.

**Comment by pacomf** [comment]
Add endpoint get_jobs in v1.6.0, to get the last jobs by user. 

https://github.com/IBM/qiskit-api-py/commit/7b4325299adb096a63f7442e88b91b3dc2daf9c6
