### ISSUE TITLE
Default experiment name does not use %H%M%S

### ISSUE THREAD

**Issue by cclauss** [IBM/qiskit-api-py#15]
- 'Experiment #20170622000000'  # current
- 'Experiment #20170622234215'  # proposed

Should https://github.com/IBM/qiskit-api-py/blob/master/IBMQuantumExperience/IBMQuantumExperience.py#L250 use `datetime.datetime.now()` instead of `datetime.date.today()` when creating the default name?  This would allow multiple uniquely named experiments in a given day.

**Comment by pacomf** [comment]
PR accepted and merged
