### ISSUE TITLE
PEP 8 naming

### ISSUE THREAD

**Issue by rob-smallshire** [IBM/qiskit-api-py#2]
I'm very surprised to see a new Python API which doesn't follow [PEP 8](https://www.python.org/dev/peps/pep-0008/) naming conventions with, for example, `runExperiment` instead of `run_experiment`.

**Comment by pacomf** [comment]
Yes, you are right @rob-smallshire , we will adapt the next version to PEP 8 :). Sorry for the inconvenience.
