### ISSUE TITLE
KeyError: 'result' during Qprogram.run

### ISSUE THREAD

**Issue by sathayen** [IBM/qiskit-api-py#27]
Issue encountered in version : 1.8
No error seen if I downgrade IBMQuantumExperience to v1.6

Steps:
1. Install all the required dependencies, including `IBMQuantumExperience v1.8`
2. Start Jupyter notebook and open the example file  [tutorial4developer.ipynb] (https://github.com/IBM/qiskit-sdk-py/blob/master/tutorial/sections/tutorial4developer.ipynb)
3. (Optional) Just for the sake of clarity, at the top of this file, insert a new code cell and just print the version of `IBMQuantumExperience` --
                  `!pip show IBMQuantumExperience`
4. Update the QConfig file with your API token 
5. Execute the notebook... while executing the following cell, 
```python
Q_program.compile(circuits, device) # Compile your program
# Run your program in the device and check the execution result every 2 seconds 
result = Q_program.run(wait=2, timeout=240)
```
it printed the following error:

> KeyErrorTraceback (most recent call last)
> ----> 4 result = Q_program.run(wait=2, timeout=240)
>..
>     540                 self.__quantum_program["circuits"][name]["execution"][backend]["status"] = job_result["qasms"][index]["status"]
> KeyError: 'result'

**If I downgrade IBMQuantumExperience to v1.6, the execution runs smoothly (no error). The following screenshots show results of execution for v1.8 vs v1.6**

**v1.8 (Error)**
![with_ibmquantumexperience_v1 8_error](https://user-images.githubusercontent.com/10127802/28719417-6fbfc3b2-7399-11e7-8167-3b8b93051c68.png)

**v1.6 (No Error)**
![with_ibmquantumexperience_v1 6](https://user-images.githubusercontent.com/10127802/28719424-7730e55e-7399-11e7-824e-9e83e1860de2.png)

**Comment by pacomf** [comment]
Yes, this is an change required by Quantum Team in the return data from jobs.
In v1.6 the result was:

```
'result': {'data': {'counts': {'00000': 555, '00001': 469},
   'time': 14.990177154541016},
  'date': '2017-07-22T02:46:55.346Z'}
```
from now the data in jobs returns:
```
'data': {'counts': {'00000': 555, '00001': 469},
   'time': 14.990177154541016},
  'date': '2017-07-22T02:46:55.346Z'
```
