### ISSUE TITLE
does the json-api differ beween ibmqx2 and ibmqx3?

### ISSUE THREAD

**Issue by ku-antum** [IBM/qiskit-api-py#28]
Sorry, if this is not the right forum, but I don't have an idea where to post:
Could there be a difference between ibmqx2 and ibmqx3 backend?

I do have beta-access (it shows in my account info on quantum-experience).

When I access the JSON-Api for ibmqx3 I always receive a "400 bad request":
```https://quantumexperience.ng.bluemix.net/api/codes/execute?access_token=<replaced>&shots=1024&deviceRunType=ibmqx3``` 

I post a very simple qasm-code that works fine, if I change the device type to ibmqx2. 
Here the very simple qasm-code that I use as test: 
```
{ "name": "r3.simple",
  "qasm": "include \"qelib1.inc\";qreg q[2];creg c[2];h q[0];h q[1];measure q -\u003e c;",
  "codeType": "QASM2"}
```

**Comment by pacomf** [comment]
Hi @ku-antum, 

   Actually, the ibmqx3 is only accesible via Job API, so you need to use the ```run_job``` and ```get_job``` methods to run experiments in the ibmqx3.

**Comment by ku-antum** [comment]
Many thanks for the hint!  This did the trick.
