### ISSUE TITLE
simulator source code release

### ISSUE THREAD

**Issue by ku-antum** [IBM/qiskit-api-py#8]
Hope this is not totally out of place here, but I asked this question before at the QuantumExperience forum and it seemed to have been overlooked there.

Is it planned to release the simulator's source code?
It would be neat to run (small) simulations off-line.

**Comment by jaygambetta** [comment]
It would be better to asked this at qiskit-sdk-py. But the answer to your question is we want to add more features like this.

**Comment by ku-antum** [comment]
Cool!
I close this issue, thanks.
